Fix submission by UUID method
ebi-ait/ingest-client pull request #28
Opened 2021-09-03 17:07 UTC by ke4

Changes:
- submission by uuid api call needs an auth token

2021-09-06 10:13 UTC, amnonkhen approved these changes

2021-09-06 10:14 UTC, amnonkhen requested changes
Should this PR be to `dev` rather than `master`?

2021-09-06 10:57 UTC, ke4 commented
@amnonkhen it is a library. We only need a master branch.

2021-09-06 10:58 UTC, amnonkhen approved these changes

2022-11-28 14:47 UTC, ke4 commented
This is an old stale PR, so I am closing it.

2022-11-28 14:47 UTC, closed without merging